# Generated by Django 6.0.6 on 2026-06-25 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("filme", "Filme"), ("serie", "Serie")], max_length=10
                    ),
                ),
                ("sinopse", models.TextField(blank=True)),
                ("ano_lancamento", models.IntegerField()),
                ("diretor", models.CharField(blank=True, max_length=100)),
                (
                    "generos",
                    models.CharField(
                        choices=[
                            ("acao", "Acao"),
                            ("comedia", "Comedia"),
                            ("terror", "Terror"),
                            ("romance", "Romance"),
                            ("drama", "Drama"),
                            ("ficcao", "Ficcao Cientifica"),
                            ("aventura", "Aventura"),
                            ("suspense", "Suspense"),
                            ("animacao", "Animacao"),
                            ("documentario", "Documentario"),
                        ],
                        default="drama",
                        max_length=50,
                    ),
                ),
                (
                    "imdb_id",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("poster_url", models.URLField(blank=True, max_length=500)),
                ("duracao", models.CharField(blank=True, max_length=50)),
                ("idioma", models.CharField(blank=True, max_length=100)),
                ("pais", models.CharField(blank=True, max_length=100)),
                ("elenco", models.TextField(blank=True)),
                ("num_temporadas", models.IntegerField(blank=True, null=True)),
                ("classificacao", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario", models.TextField(blank=True)),
                ("dt_avaliacao", models.DateTimeField(auto_now_add=True)),
                ("dt_atualizacao", models.DateTimeField(auto_now=True)),
                ("assistido_em", models.DateField(blank=True, null=True)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "midia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="midias.midia",
                    ),
                ),
            ],
            options={
                "ordering": ["-dt_avaliacao"],
                "unique_together": {("pessoa", "midia")},
            },
        ),
    ]
